$env:PYTHONPATH = "C:\Users\alpes\OneDrive\Documents\Important Projects\optiinfra"
$env:POSTGRES_HOST = "localhost"
$env:POSTGRES_PORT = "5432"
$env:POSTGRES_DB = "optiinfra"
$env:POSTGRES_USER = "optiinfra"
$env:POSTGRES_PASSWORD = "optiinfra_dev_password"
$env:CLICKHOUSE_HOST = "localhost"
$env:CLICKHOUSE_PORT = "8123"
$env:CLICKHOUSE_DB = "optiinfra"
$env:QDRANT_HOST = "localhost"
$env:QDRANT_PORT = "6333"
$env:REDIS_HOST = "localhost"
$env:REDIS_PORT = "6379"
python -m src.main
